/*
  # LeadFlow CRM — Full Schema

  1. New Tables
    - `workspaces` — Organization/workspace container
    - `workspace_members` — Users belonging to a workspace with roles
    - `profiles` — Extended user profile data linked to auth.users
    - `funnel_stages` — Kanban pipeline stages per workspace
    - `custom_field_definitions` — Custom fields per workspace
    - `leads` — Lead records per workspace
    - `lead_custom_values` — Custom field values for leads
    - `stage_required_fields` — Required fields for stage transitions
    - `campaigns` — Automated message campaigns per workspace
    - `generated_messages` — Messages generated by campaigns
    - `activity_log` — Audit trail of all actions

  2. Security
    - RLS enabled on ALL tables
    - Policies restrict access to authenticated users who are members of the workspace
    - No public access — all tables require authentication + workspace membership

  3. Important Notes
    - All tables use UUID primary keys with gen_random_uuid()
    - Timestamps default to now()
    - Foreign keys enforce referential integrity
    - Cascade deletes where appropriate (workspace deletion cascades)
*/

-- Workspaces
CREATE TABLE IF NOT EXISTS workspaces (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name       text NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- Profiles (extends auth.users)
CREATE TABLE IF NOT EXISTS profiles (
  id        uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name text DEFAULT '',
  email     text DEFAULT '',
  created_at timestamptz DEFAULT now()
);

-- Workspace members
CREATE TABLE IF NOT EXISTS workspace_members (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  user_id      uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role         text NOT NULL DEFAULT 'member' CHECK (role IN ('admin', 'member')),
  created_at   timestamptz DEFAULT now(),
  UNIQUE(workspace_id, user_id)
);

-- Funnel stages
CREATE TABLE IF NOT EXISTS funnel_stages (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  name         text NOT NULL,
  position     int NOT NULL DEFAULT 0,
  color        text NOT NULL DEFAULT '#6366f1',
  created_at   timestamptz DEFAULT now()
);

-- Custom field definitions
CREATE TABLE IF NOT EXISTS custom_field_definitions (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  name         text NOT NULL,
  field_type   text NOT NULL DEFAULT 'text' CHECK (field_type IN ('text', 'number', 'date', 'select')),
  options      text[] DEFAULT '{}',
  position     int NOT NULL DEFAULT 0,
  created_at   timestamptz DEFAULT now()
);

-- Leads
CREATE TABLE IF NOT EXISTS leads (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  stage_id     uuid NOT NULL REFERENCES funnel_stages(id) ON DELETE RESTRICT,
  assigned_to  uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  name         text NOT NULL DEFAULT '',
  email        text DEFAULT '',
  phone        text DEFAULT '',
  company      text DEFAULT '',
  job_title    text DEFAULT '',
  source       text DEFAULT '',
  notes        text DEFAULT '',
  created_at   timestamptz DEFAULT now(),
  updated_at   timestamptz DEFAULT now()
);

-- Lead custom field values
CREATE TABLE IF NOT EXISTS lead_custom_values (
  id       uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_id  uuid NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  field_id uuid NOT NULL REFERENCES custom_field_definitions(id) ON DELETE CASCADE,
  value    text DEFAULT '',
  UNIQUE(lead_id, field_id)
);

-- Stage required fields
CREATE TABLE IF NOT EXISTS stage_required_fields (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  stage_id        uuid NOT NULL REFERENCES funnel_stages(id) ON DELETE CASCADE,
  standard_field  text,
  custom_field_id uuid REFERENCES custom_field_definitions(id) ON DELETE CASCADE,
  created_at      timestamptz DEFAULT now()
);

-- Campaigns
CREATE TABLE IF NOT EXISTS campaigns (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id     uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  trigger_stage_id uuid REFERENCES funnel_stages(id) ON DELETE SET NULL,
  name             text NOT NULL DEFAULT '',
  context          text DEFAULT '',
  prompt           text DEFAULT '',
  is_active        boolean DEFAULT false,
  created_at       timestamptz DEFAULT now()
);

-- Generated messages
CREATE TABLE IF NOT EXISTS generated_messages (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_id        uuid NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  campaign_id    uuid NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  variations     text[] DEFAULT '{}',
  was_sent       boolean DEFAULT false,
  sent_at        timestamptz,
  sent_variation int,
  auto_generated boolean DEFAULT false,
  created_at     timestamptz DEFAULT now()
);

-- Activity log
CREATE TABLE IF NOT EXISTS activity_log (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id  uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  lead_id       uuid REFERENCES leads(id) ON DELETE SET NULL,
  user_id       uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  activity_type text NOT NULL CHECK (activity_type IN ('lead_created', 'stage_changed', 'message_generated', 'message_sent', 'lead_updated')),
  metadata      jsonb DEFAULT '{}',
  created_at    timestamptz DEFAULT now()
);

-- Enable RLS on all tables
ALTER TABLE workspaces ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE workspace_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE funnel_stages ENABLE ROW LEVEL SECURITY;
ALTER TABLE custom_field_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE lead_custom_values ENABLE ROW LEVEL SECURITY;
ALTER TABLE stage_required_fields ENABLE ROW LEVEL SECURITY;
ALTER TABLE campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE generated_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE activity_log ENABLE ROW LEVEL SECURITY;

-- Helper function: check if user is member of workspace
CREATE OR REPLACE FUNCTION is_workspace_member(ws_id uuid)
RETURNS boolean AS $$
  SELECT EXISTS (
    SELECT 1 FROM workspace_members
    WHERE workspace_id = ws_id AND user_id = auth.uid()
  )
$$ LANGUAGE sql SECURITY DEFINER STABLE;

-- Profiles policies
CREATE POLICY "Users can read own profile"
  ON profiles FOR SELECT
  TO authenticated
  USING (auth.uid() = id);

CREATE POLICY "Users can update own profile"
  ON profiles FOR UPDATE
  TO authenticated
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can insert own profile"
  ON profiles FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = id);

-- Workspaces policies
CREATE POLICY "Members can view workspaces"
  ON workspaces FOR SELECT
  TO authenticated
  USING (is_workspace_member(id));

CREATE POLICY "Admins can update workspaces"
  ON workspaces FOR UPDATE
  TO authenticated
  USING (is_workspace_member(id) AND EXISTS (
    SELECT 1 FROM workspace_members
    WHERE workspace_id = id AND user_id = auth.uid() AND role = 'admin'
  ))
  WITH CHECK (is_workspace_member(id) AND EXISTS (
    SELECT 1 FROM workspace_members
    WHERE workspace_id = id AND user_id = auth.uid() AND role = 'admin'
  ));

CREATE POLICY "Authenticated users can create workspaces"
  ON workspaces FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Workspace members policies
CREATE POLICY "Members can view workspace members"
  ON workspace_members FOR SELECT
  TO authenticated
  USING (is_workspace_member(workspace_id));

CREATE POLICY "Admins can insert workspace members"
  ON workspace_members FOR INSERT
  TO authenticated
  WITH CHECK (is_workspace_member(workspace_id) AND EXISTS (
    SELECT 1 FROM workspace_members
    WHERE workspace_id = workspace_members.workspace_id AND user_id = auth.uid() AND role = 'admin'
  ));

CREATE POLICY "Admins can delete workspace members"
  ON workspace_members FOR DELETE
  TO authenticated
  USING (is_workspace_member(workspace_id) AND EXISTS (
    SELECT 1 FROM workspace_members
    WHERE workspace_id = workspace_members.workspace_id AND user_id = auth.uid() AND role = 'admin'
  ));

-- Funnel stages policies
CREATE POLICY "Members can view stages"
  ON funnel_stages FOR SELECT
  TO authenticated
  USING (is_workspace_member(workspace_id));

CREATE POLICY "Admins can insert stages"
  ON funnel_stages FOR INSERT
  TO authenticated
  WITH CHECK (is_workspace_member(workspace_id));

CREATE POLICY "Admins can update stages"
  ON funnel_stages FOR UPDATE
  TO authenticated
  USING (is_workspace_member(workspace_id))
  WITH CHECK (is_workspace_member(workspace_id));

CREATE POLICY "Admins can delete stages"
  ON funnel_stages FOR DELETE
  TO authenticated
  USING (is_workspace_member(workspace_id));

-- Custom field definitions policies
CREATE POLICY "Members can view custom fields"
  ON custom_field_definitions FOR SELECT
  TO authenticated
  USING (is_workspace_member(workspace_id));

CREATE POLICY "Admins can insert custom fields"
  ON custom_field_definitions FOR INSERT
  TO authenticated
  WITH CHECK (is_workspace_member(workspace_id));

CREATE POLICY "Admins can update custom fields"
  ON custom_field_definitions FOR UPDATE
  TO authenticated
  USING (is_workspace_member(workspace_id))
  WITH CHECK (is_workspace_member(workspace_id));

CREATE POLICY "Admins can delete custom fields"
  ON custom_field_definitions FOR DELETE
  TO authenticated
  USING (is_workspace_member(workspace_id));

-- Leads policies
CREATE POLICY "Members can view leads"
  ON leads FOR SELECT
  TO authenticated
  USING (is_workspace_member(workspace_id));

CREATE POLICY "Members can insert leads"
  ON leads FOR INSERT
  TO authenticated
  WITH CHECK (is_workspace_member(workspace_id));

CREATE POLICY "Members can update leads"
  ON leads FOR UPDATE
  TO authenticated
  USING (is_workspace_member(workspace_id))
  WITH CHECK (is_workspace_member(workspace_id));

CREATE POLICY "Members can delete leads"
  ON leads FOR DELETE
  TO authenticated
  USING (is_workspace_member(workspace_id));

-- Lead custom values policies
CREATE POLICY "Members can view lead custom values"
  ON lead_custom_values FOR SELECT
  TO authenticated
  USING (EXISTS (
    SELECT 1 FROM leads WHERE leads.id = lead_custom_values.lead_id AND is_workspace_member(leads.workspace_id)
  ));

CREATE POLICY "Members can insert lead custom values"
  ON lead_custom_values FOR INSERT
  TO authenticated
  WITH CHECK (EXISTS (
    SELECT 1 FROM leads WHERE leads.id = lead_custom_values.lead_id AND is_workspace_member(leads.workspace_id)
  ));

CREATE POLICY "Members can update lead custom values"
  ON lead_custom_values FOR UPDATE
  TO authenticated
  USING (EXISTS (
    SELECT 1 FROM leads WHERE leads.id = lead_custom_values.lead_id AND is_workspace_member(leads.workspace_id)
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM leads WHERE leads.id = lead_custom_values.lead_id AND is_workspace_member(leads.workspace_id)
  ));

CREATE POLICY "Members can delete lead custom values"
  ON lead_custom_values FOR DELETE
  TO authenticated
  USING (EXISTS (
    SELECT 1 FROM leads WHERE leads.id = lead_custom_values.lead_id AND is_workspace_member(leads.workspace_id)
  ));

-- Stage required fields policies
CREATE POLICY "Members can view stage required fields"
  ON stage_required_fields FOR SELECT
  TO authenticated
  USING (EXISTS (
    SELECT 1 FROM funnel_stages WHERE funnel_stages.id = stage_required_fields.stage_id AND is_workspace_member(funnel_stages.workspace_id)
  ));

CREATE POLICY "Admins can insert stage required fields"
  ON stage_required_fields FOR INSERT
  TO authenticated
  WITH CHECK (EXISTS (
    SELECT 1 FROM funnel_stages WHERE funnel_stages.id = stage_required_fields.stage_id AND is_workspace_member(funnel_stages.workspace_id)
  ));

CREATE POLICY "Admins can delete stage required fields"
  ON stage_required_fields FOR DELETE
  TO authenticated
  USING (EXISTS (
    SELECT 1 FROM funnel_stages WHERE funnel_stages.id = stage_required_fields.stage_id AND is_workspace_member(funnel_stages.workspace_id)
  ));

-- Campaigns policies
CREATE POLICY "Members can view campaigns"
  ON campaigns FOR SELECT
  TO authenticated
  USING (is_workspace_member(workspace_id));

CREATE POLICY "Members can insert campaigns"
  ON campaigns FOR INSERT
  TO authenticated
  WITH CHECK (is_workspace_member(workspace_id));

CREATE POLICY "Members can update campaigns"
  ON campaigns FOR UPDATE
  TO authenticated
  USING (is_workspace_member(workspace_id))
  WITH CHECK (is_workspace_member(workspace_id));

CREATE POLICY "Members can delete campaigns"
  ON campaigns FOR DELETE
  TO authenticated
  USING (is_workspace_member(workspace_id));

-- Generated messages policies
CREATE POLICY "Members can view generated messages"
  ON generated_messages FOR SELECT
  TO authenticated
  USING (EXISTS (
    SELECT 1 FROM leads WHERE leads.id = generated_messages.lead_id AND is_workspace_member(leads.workspace_id)
  ));

CREATE POLICY "Members can insert generated messages"
  ON generated_messages FOR INSERT
  TO authenticated
  WITH CHECK (EXISTS (
    SELECT 1 FROM leads WHERE leads.id = generated_messages.lead_id AND is_workspace_member(leads.workspace_id)
  ));

CREATE POLICY "Members can update generated messages"
  ON generated_messages FOR UPDATE
  TO authenticated
  USING (EXISTS (
    SELECT 1 FROM leads WHERE leads.id = generated_messages.lead_id AND is_workspace_member(leads.workspace_id)
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM leads WHERE leads.id = generated_messages.lead_id AND is_workspace_member(leads.workspace_id)
  ));

-- Activity log policies
CREATE POLICY "Members can view activity log"
  ON activity_log FOR SELECT
  TO authenticated
  USING (is_workspace_member(workspace_id));

CREATE POLICY "Members can insert activity log"
  ON activity_log FOR INSERT
  TO authenticated
  WITH CHECK (is_workspace_member(workspace_id));

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_workspace_members_user ON workspace_members(user_id);
CREATE INDEX IF NOT EXISTS idx_workspace_members_workspace ON workspace_members(workspace_id);
CREATE INDEX IF NOT EXISTS idx_leads_workspace ON leads(workspace_id);
CREATE INDEX IF NOT EXISTS idx_leads_stage ON leads(stage_id);
CREATE INDEX IF NOT EXISTS idx_leads_assigned ON leads(assigned_to);
CREATE INDEX IF NOT EXISTS idx_funnel_stages_workspace ON funnel_stages(workspace_id);
CREATE INDEX IF NOT EXISTS idx_campaigns_workspace ON campaigns(workspace_id);
CREATE INDEX IF NOT EXISTS idx_activity_log_workspace ON activity_log(workspace_id);
CREATE INDEX IF NOT EXISTS idx_activity_log_lead ON activity_log(lead_id);
CREATE INDEX IF NOT EXISTS idx_generated_messages_lead ON generated_messages(lead_id);
CREATE INDEX IF NOT EXISTS idx_generated_messages_campaign ON generated_messages(campaign_id);

-- Trigger to auto-create profile on user signup
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO profiles (id, full_name, email)
  VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'full_name', ''), COALESCE(NEW.email, ''));
  RETURN NEW;
END
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION handle_new_user();
